[package]
name = "crunchyroll-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

# Internal! Do not use it outside of testing
__test_strict = []

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
derive_builder = "0.11"
impls = "1.0"
m3u8-rs = "5.0"
reqwest = { version = "0.11", features = ["cookies", "json", "serde_json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7"
smart-default = "0.6"

[dev-dependencies]
once_cell = "1.13"
tokio = { version = "1.20", features = ["rt", "macros"] }
