[package]
name = "crunchyroll-rs"
version = "0.1.0"
authors = ["Crunchy Labs Maintainers"]
edition = "2021"
description = "Pure Rust implementation of the crunchyroll api."
readme = "README.md"
repository = "https://github.com/crunchy-labs/crunchyroll-rs"
license = "MIT OR Apache-2.0"
keywords = ["crunchyroll", "anime", "downloader"]
categories = ["api-bindings"]

[features]
default = ["stream", "parse", "static-curl"]

# Add functionality to stream episodes / movies so you can process the unencrypted streaming data further, e.g. write it
# to a file and then play it.
stream = ["aes", "cbc", "m3u8-rs"]
# Add functionality to parse Crunchyroll urls.
parse = ["regex"]

# Embed curl statically into the library instead of using a system provided shared library.
static-curl = ["isahc/static-curl"]
# Embed openssl statically into the library instead of using a system provided shared library. If you have problems
# while building this library against a musl based linux system, this feature might solve them.
static-ssl = ["isahc/static-ssl"]

# Internal! Do not use it outside of testing
__test_strict = []

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
http = "0.2"
isahc = { git = "https://github.com/sagebind/isahc", rev = "34f158ef", features = ["cookies"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7"
smart-default = "0.6"
tokio = { version = "1.22", features = ["sync"] }

crunchyroll-rs-internal = { version = "0.1", path = "internal" }

# Optional / required from features
aes = { version = "0.8", optional = true }
cbc = { version = "0.1", optional = true }
m3u8-rs = { version = "5.0", optional = true }
regex = { version = "1.7", default-features = false, features = ["std"], optional = true }

[dev-dependencies]
anyhow = "1.0"
once_cell = "1.16"
rand = "0.8"
tokio = { version = "1.22", features = ["macros", "rt", "rt-multi-thread"] }

[workspace]
members = ["internal"]
