[package]
name = "crunchyroll-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

__test_strict = []

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
derive_builder = "0.11"
reqwest = { version = "0.11", features = ["cookies", "json", "serde_json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7"
smart-default = "0.6"

[dev-dependencies]
tokio = { version = "1.20", features = ["rt", "macros"] }

[profile.release]
lto = true
panic = "abort"
opt-level = "z"
