[package]
name = "crunchyroll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["stream", "parse"]

# Add functionality to stream episodes / movies so you can process the unencrypted streaming data further, e.g. write it
# to a file and then play it.
stream = ["aes", "cbc", "m3u8-rs"]
# Add functionality to parse Crunchyroll urls.
parse = ["regex"]

# Internal! Do not use it outside of testing
__test_strict = []

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11", features = ["cookies", "json", "gzip"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7"
smart-default = "0.6"
tokio = "1.21"

proc-macro = { path = "proc-macro" }

# Optional / required from features
aes = { version = "0.8", optional = true }
cbc = { version = "0.1", optional = true }
m3u8-rs = { version = "5.0", optional = true }
regex = { version = "1.6", default-features = false, features = ["std"], optional = true }

[dev-dependencies]
anyhow = "1.0"
once_cell = "1.13"
rand = "0.8"
tokio = { version = "1.21", features = ["macros", "rt", "rt-multi-thread"] }
