[package]
name = "proc-macro"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
darling = "0.14"
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
