name: ci

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env: 
        ETP_RT: ${{ secrets.ETP_RT }}
      # *stream* and *playback* tests are working locally with GH actions they fail even though the same command
      # and the same credentials for login are used
      run: cargo test --verbose --features __test_strict --no-fail-fast -- --test-threads=1 --skip login_with_credentials --skip login_with_session_id --skip stream --skip playback
