name: ci

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        env:
          ETP_RT: ${{ secrets.ETP_RT }}
        run: cargo test --verbose --tests --no-fail-fast --features __test_strict -- --test-threads=1 --skip login_with_credentials --skip login_with_access_token --skip login_with_refresh_token --skip login_with_session_id
