name: ci

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  ETP_RT: ${{ secrets.ETP_RT }}

jobs:
  test-login-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: vcpkg install openssl:x64-windows-static-md

      - name: Set env variables
        shell: bash
        run: echo "CFLAGS=-I$(echo $VCPKG_INSTALLATION_ROOT)\packages\openssl_x64-windows-static-md\include" >> $GITHUB_ENV

      - name: Cargo cache # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-pc-windows-msvc
          default: true

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: login_with_etp_rt --all-features

  test-full:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cargo cache # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.toolchain }}
          default: true

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --tests --no-fail-fast --all-features -- --test-threads=1 --skip login_with_credentials --skip login_with_access_token --skip login_with_refresh_token --skip login_with_session_id
