name: publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # I had a check here if the versions are already existing but magically with gh actions it returned a false
      # positive.

      - name: Publish main
        run: |
          DRY_RUN=${{ github.event.inputs.dry_run }}
          DRY_RUN=${DRY_RUN:-"false"}
          cargo publish $(if $DRY_RUN; then echo "--dry-run"; fi) --token ${{ secrets.CRATES_TOKEN }}

      - name: Publish internal
        run: |
          DRY_RUN=${{ github.event.inputs.dry_run }}
          DRY_RUN=${DRY_RUN:-"false"}
          cd internal && cargo publish $(if $DRY_RUN; then echo "--dry-run"; fi) --token ${{ secrets.CRATES_TOKEN }}
