name: publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install cargo show
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-show

      - name: Check if main version exists
        if: ${{ github.event.inputs.dry_run == 'false' }}
        run: if cargo show crunchyroll-rs --json | grep -q -E "\"num\":\w*\"$(git describe --tags --abbrev=0 --match 'v*' 2> /dev/null | cut -c 2-)"; then echo "Main version already exists" && exit 1; fi

      - name: Check main if internal version exists
        if: ${{ github.event.inputs.dry_run == 'false' }}
        run: if cargo show crunchyroll-rs-internal --json | grep -q -E "\"num\":\w*\"$(git describe --tags --abbrev=0 --match 'v*' 2> /dev/null | cut -c 2-)"; then echo "Internal version already exists" && exit 1; fi

      - name: Publish main
        run: |
          DRY_RUN=${{ github.event.inputs.dry_run }}
          DRY_RUN=${DRY_RUN:-"false"}
          cargo publish $(if $DRY_RUN; then echo "--dry-run"; fi) --token ${{ secrets.CRATES_TOKEN }}

      - name: Publish internal
        run: |
          DRY_RUN=${{ github.event.inputs.dry_run }}
          DRY_RUN=${DRY_RUN:-"false"}
          cd internal && cargo publish $(if $DRY_RUN; then echo "--dry-run"; fi) --token ${{ secrets.CRATES_TOKEN }}
